### ISSUE TITLE
Tracker Data - Wrong SessionState

### ISSUE THREAD

**Issue by sv3nk** [cmbruns/pyopenxr_examples#13]
I am having trouble with the tracker example and the reason is that the application never goes into the correct xr.SessionState

When looping over rendered frames, you check the following:
`if context.session_state == xr.SessionState.FOCUSED:`

However, when I check the sessionState each frame, it is actually:
`xr.SessionState.SYNCHRONIZED`

Therefore, the example loops over the frames but never enters the if-statement

I looked at the session lifecycle but could not find a way to get it into the correct state:
https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#session-lifecycle

Any help would be greatly appreciated.

**Comment by cmbruns** [comment]
I believe examples using trackers require the use of OpenXR Actions. Actions can only be used in the FOCUSED state. My HTC Vive headset won't enter the FOCUSED state unless it thinks I am actively wearing the headset. I stick a piece of cardboard in front of the face sensor on the headset, so I can test these things without having to wear the headset. Maybe the same trick would work for you.

An alternative is the use the HEADLESS extension. I've been meaning to publish some headless examples but my focus is on other things at the moment.

**Comment by sv3nk** [comment]
Great thanks for the fast reply. That clears things up :)
